#!/bin/bash

fansodir=`dirname $0`

if [ ! -z $1 ]
then
  abspath=`readlink -f $1`
  filename=`basename $abspath`
  filepath=`dirname $abspath`
else
  filepath=$PWD
fi

cd $fansodir
octave -q --persist --no-gui fanso.m $filepath $filename
